interface PlotPositionInterface {

    // DB assigned ID. Should only be generated by DB, therfore is readonly.
    readonly id?: string;

    // Radial position value. Unit: mm. Represents the distance from the center of the position to the center of the DemeBot center pivot.
    r: number;

    // Theta angle value. Unit: degrees. Respresents the angular distance from the DemeBot's most rclockwise reach to the position the DemeBot's arms must be to reach the posistion.
    t: number;

    // Z position value. Unit: mm. Represents the vertical distance of the position.
    z: number;

    // Maxiumum height in mm the plant is expected to grow.
    ended_at?: Date;

    // Maxiumum height in mm the plant is expected to grow.
    created_at?: Date;

}

export default PlotPositionInterface;